### PR TITLE
Clean the image

### PR DESCRIPTION
**Pull request by AaronDewes**
Do not merge this yet, I still need to wait for a new base image to finish building

### CODE REVIEW

**Comment by EddWills95** [comment]
Did this build okay?

**Comment by AaronDewes** [comment]
It did, the base is still about 670MB, which is way too large, but it's a bit smaller at least

**Comment by AaronDewes** [comment]
It acutally is smaller, I pushed to the wrong container (typo), sorry, but will take another hour

**Comment by AaronDewes** [comment]
This PR can be merged if the arm64 build here succeeds: https://github.com/AaronDewes2/python-grpc/actions/runs/486458079. The base is actually only 62.53 MB

**Comment by AaronDewes** [comment]
It works now, the image is about 110MB now, which is a big improvement over the current 670MB.

**Comment by EddWills95** [comment]
Amazing stuff!

**Pull request merged**
